spring:
  application:
    name: config    #当前项目名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Mrkongjava/config-repo.git   #github仓库地址（加载git配置文件）
          username: Mrkongjava  #github账号
          password: k1083536928    #github登录密码
          basedir: D:/Java/testConfig    #配置从git拉取下来的文件存放的路径(程序还会在该目录下创建一个本地的git仓库)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/    #eureka注册地址
#smanagement:
#  endpoints:
#    web:
#      expose: "*"
